Initial implementation
ckeditor/ckeditor5-page-break pull request #1
Opened 2019-09-12 11:49 UTC by pomek

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Initial implementation. Closes ckeditor/ckeditor5#1194.

---

### Additional information

We need to improve the demo but it can be done outside this PR.

2019-09-19 09:23 UTC, pomek commented
I improved the demo snippet. I added a button that opens a print preview window after clicking:

![image](https://user-images.githubusercontent.com/2270764/65231373-c59d0c00-dacf-11e9-83ef-658f60aeb146.png)

For the above content, it will show something like on the picture below:

![image](https://user-images.githubusercontent.com/2270764/65231313-b027e200-dacf-11e9-9cfd-6a931d4c4ee9.png)

2019-09-19 09:23 UTC, pomek commented
@dkonopka, could you check whether the `pageBreak` widget is being rendered correctly with float images?

2019-09-19 11:46 UTC, dkonopka commented
WFM 👍

2019-09-26 09:25 UTC, mlewand requested changes
Overall looks fine.

I don't know why data is downcasted the way it is thoug, see the review comments for more details.

@Msgy I'd like to ask you to give it a quick testing. It is very similar to the horizontal rule (line) feature, but I'd still love to have another pair of eyes to check it.

@pomek Please make a 0.0.1 pre-release so that CI already kicks in.

2019-09-26 09:25 UTC, mlewand commented on src/pagebreakediting.js
> +					style: 'display: none'
What is the reason for using a `span` here? Why can't we just go with a `<div>` alone?

I checked CKE4 and didn't find answer for this in the code comments. Also blame didn't show up anything interesting.

If we don't really need this we should create a page break when there's `span` inside our `div` (for compatibility with CKE4) but the output data should then be a simpler `span`-less form.

2019-09-26 09:25 UTC, mlewand commented on src/pagebreakui.js
> +				isToggleable: true
This is not a toggle button.

2019-09-26 09:25 UTC, mlewand commented on docs/_snippets/features/page-break.html
> +<button type="button" id="print-data-action">Print editor data</button>
It might be a good idea to label it "Print preview dialog", I find that current label might cause user to feel that it will be printed right of the bat - so they won't click it 😀

Any thoughts on this? @AnnaTomanek

2019-09-26 09:27 UTC, mlewand commented on docs/_snippets/features/page-break.html
> +<button type="button" id="print-data-action">Print editor data</button>
Just to give a better context, here's a screenshot of rendered content:

![image](https://user-images.githubusercontent.com/5353898/65676607-7f582780-e050-11e9-8066-2a6a9ccb9119.png)

2019-09-26 10:28 UTC, AnnaTomanek commented on docs/_snippets/features/page-break.html
> +<button type="button" id="print-data-action">Print editor data</button>
I'd suggest to use "Open print preview" - it's better to have a clear CTA with a verb than a descriptive button.

2019-09-27 06:52 UTC, pomek commented on src/pagebreakediting.js
> +					style: 'display: none'
An empty `div` is visible in the text and has a height defined as the value of `line-height` px. A div with the span inside takes 0px height.

![image](https://user-images.githubusercontent.com/2270764/65748339-fb5f7780-e103-11e9-8099-983c957e423f.png)

2019-09-30 09:33 UTC, mlewand commented on src/pagebreakediting.js
> +					style: 'display: none'
And thus it will look nice if developer doesn't add `content.css` matching CKE5. It's a valid justification for me 👌

2019-09-30 10:18 UTC, mlewand approved these changes
Looks fine now.

While doing 47135ef32f677acd39fd9d399ae6e9d7cd33465e you didn't adjust the TC in https://github.com/ckeditor/ckeditor5-page-break/blob/a8b6d7b/tests/pagebreakui.js#L47 which caused tests to fail. I'll fix that as a part of R.

I also added a reference to your comment explaining putting `span` inside a `div`.

2019-09-30 10:20 UTC, merged